apiVersion: v1
kind: Pod
metadata: 
  name: never-pod
  labels:
    app: resart-policy
spec:
  restartPolicy: Always
  containers: 
    - name: busybox
      image: busybox
      command: ['sh','-c','sleep 10;this will fail']
#selfHealing pod