apiVersion: v1
kind: Pod
metadata: 
  name: ikiz
  labels:
    app: ikiz
spec:
  containers:
    - name: kutu1
      image: radial/busyboxplus:curl
      command: ["sh","-c","sleep 3600"]
    - name: nginx
      image: nginx